# 提供云环境冒着风险方便大家演示用，切勿修改配置，开发定位错误和大家使用比较麻烦，望理解。
# 如果要改配置搭建下本地环境哈，步骤在项目说明README
# 项目对你有帮助麻烦给个❤，感激不尽！https://github.com/hxrui
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: 'http://localhost:8000/getPublicKey'
  redis:
    database: 0
    host: localhost
    port: 6379
    password: 5601564a
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 启用服务发现
          lower-case-service-id: true
      routes:
        - id: youlai-auth
          uri: lb://youlai-auth
          predicates:
            - Path=/youlai-auth/**
          filters:
            - StripPrefix=1
        - id: youlai-admin
          uri: lb://youlai-admin
          predicates:
            - Path=/youlai-admin/**
          filters:
            - StripPrefix=1
        - id: intasect-service
            uri: lb://intasect-service
            predicates:
              - Path=/intasect-service/**
            filters:
              - StripPrefix=1

# 配置白名单路径(无需登录)
whitelist:
  urls:
      - "/youlai-auth/oauth/token"

# 是否演示环境
demo: false